# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad118b956728145c36e6bc27df59cebb797e8d57554437fd92d8e49c639ac2fe6c99e388197d5fedd509db7092f696e938b9c47df7c412cd8cb2be551b15890c

test:
  secret_key_base: 37bc01d1e40f6ed693bc85a963d2132878ae4d9edb84c5b374ef73574fc5e811631ff5328eadc157b0c5dfafd7ce988343fafa3d7e1f0414d3a65767eb96cb01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
